# Welcome to Jekyll!
#

# Site settings
title: GeoSpatial Experts
description: |
  From field data colleciton 
  ... to final reports 
  
  Collect photographic evidence of conditions or 
  assets in the field. Take a picture & fill out 
  a form on a mobile device - automatically transfer 
  data to the office to create reports, photo maps, 
  or push to your database.
owner: GeoSpatial Experts # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: Info@GeoSpatialExperts.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
